main: dihydrogen\monoxide\factions\FactionsPP
api:
  - 3.0.0-ALPHA4
  - 3.0.0-ALPHA5

name: FactionsPP
description: A factions plugin
version: 0.0.1_ALPHA-dev#1
authors:
  - JackNoordhuis

permissions:
  factionspp:
    description: "Main factions-pp permission node"
    default: false
    children:
      factionspp.command:
        description: "Access to all factions-pp commands"
        default: op
        children:
          factionspp.command.factions:
            description: "Access to the factions command"
            default: true
            children:
              factionspp.command.help:
                description: "Access to the help sub-command"
                default: true
