main: HittmanA\factionspp\MainClass
api: [3.0.0-ALPHA10]

name: FactionsPP
description: A factions plugin
version: 0.9.5
author: HittmanA

commands:
  factionspp:
    description: Main FactionsPP command
    usage: "/factionspp <subcommand>"
    aliases: [f, fpp]
    permission: fpp

permissions:
 fpp:
  default: true
  description: Allows to control of FPP
  children:
    fpp.command.*:
        default: true
        description: Allows use of all FPP commands
        children:
            fpp.command.create:
                default: true
                dexcription: Allows users to create new factions
        
